DROP TABLE IF EXISTS MESSAGERS;
CREATE TABLE MESSAGERS(
        ID INT AUTO_INCREMENT  PRIMARY KEY ,
        NAME VARCHAR(255),
        MESSAGERS VARCHAR(1000),
        DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

